---
# Nginx seaded - kehtivad KÃ•IGILE webservers grupis
nginx_port: 80
nginx_root: "/var/www/html"
nginx_user: "www-data"
nginx_worker_connections: 2048

# Rakenduse info
app_name: "MinuApp"
app_environment: "production"
